development: &development
  adapter: postgresql
  encoding: unicode
  database: projectmonitor_development
  host: dvmysql01
  username: fs_admin
  password: step

test:
  <<: *development
  database: projectmonitor_test

production:
  <<: *development
  database: projectmonitor_production

